ydataai/ydata-profiling

- .gitignore
- .idea/vcs.xml
- README.md
- pandas_profiling/__init__.py
- create new method get_rejected_variables() to output rejected variable (default threhold is 0.90, which is same with the threshold generated in html report)
- add usage code example of the added method in README.md
- update .gitignore to ignore files generated by pycharm
> create new method to retrieve a list of rejected variables

- pandas_profiling/base.py
- pandas_profiling/formatters.py
- pandas_profiling/templates.py
- pandas_profiling/tests.py
Previously, if you ran pandas_profiling on a DataFrame with numpy infinite values, you would get the error `ValueError: range parameter must be finite.` from the call to `plot = series.plot(kind='hist')` in `describe_numeric_1d()` in `base.py`. For example:
```
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df['A'][0] = np.inf
pandas_profiling.ProfileReport(df)
```
We now replace infinite values with NaNs:
```
data.replace(to_replace=[np.inf, np.NINF, np.PINF], value=np.nan, inplace=True)
```
and while we're at it, we alert the user to the presence of these values in the profile report.
> Add support for numpy infinite values

- pandas_profiling/base.py
Thanks for this module. It's saved me a lot of time in working on a script for profiling databases.
In running this inside another python script on multiple tables in a database I would encounter "too many files open" error after it processed enough columns. The problem seems to be the threads were staying open and in turn keeping a file descriptor open. Once enough threads had been started it would hit the OS's limit on open files.
This additional line should fix the problem.
> added call to pool.close() in describe_1d

- pandas_profiling/base.py
#36 fixed. Using `distutils.version.LooseVersion` to check version of matplotlib. No added dependencies.
> Fixed MatplotlibDeprecationWarning

- pandas_profiling/base.py
- pandas_profiling/tests.py
Thanks for this package. We are evaluating it for project and finding it suits our needs. 
In our use case we want to profile rather large database tables. We found that the correlation checks can use a lot of memory causing the process to fail. Since this check isn't critical to this use case, we would simply like to skip these checks when profiling. 
This pull request adds a keyword argument to `describe` called `check_correlation` that defaults to `True`. If `False` is passed, then the correlation checks aren't run.
> Add keyword arg to not check correlation.

- pandas_profiling/base.py
- pandas_profiling/tests.py
The current implementation includes na in distinct_count. But when the percentage of unique values is computed the distinct count is divided by the count that does not include na This is the cause of the inconsistent results highlighted in #56. I've fixed the implementation to be consistent: na is considered as a distinct value also in the percentage of unique values Another implementation would have been to not consider na at all. A specific test case has been added.
> Fixed issue #56

- pandas_profiling/__init__.py
This fixes issue #11. In his example, the dataset doesn't compute the correlation, so if the attribute doesn't exist, we should return an empty array.
> Instead of throwing an error check if the correlation was computed

- pandas_profiling/plot.py
Keep receiving matplotlib.use(BACKEND) issue. Change the backend by dynamic setting by using `matplotlib.get_backend()`. This PR is also related to a known issue #119
> Fix matplotlib backend issue with python 3.6

- pandas_profiling/report.py
Fixes a minor issue where generating the profiling report would fail if `max_freq` ends up being 0. In that case `freq / max_freq` would be `NaN`, and converting `NaN` to int fails with an exception, breaking report generation.
> Handle max_freq == 0 in _format_row

- pandas_profiling/report.py
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection
__unicode()__ was removed from Python 3 because all strs are Unicode.
> Use feature detection instead of version detection

- pandas_profiling/plot.py
A simple fix to the problem when NaT values in a dataframe result in having histogram bins for year 1680. 
This makes the histogram very uninformative. 
After the fix, only proper datetime values contribute to all the time histograms.
> Fixed wrong NaT hist bins in plot.py

- pandas_profiling/report.py
When there are no numeric columns in the dataframe, ProfileReport() errors with a zero division error. Fix this issue (#143) by checking if the correlations dataframe is empty, before generating the correlation plot.
> fix zero division error when there are no numeric columns (fixes #143)

- pandas_profiling/base.py
if the only unique not-nan value is False in a column
```python
base.get_groupby_statistic(data)
```
returns
```python
[Series([], Name: isVideoAd, dtype: int64), 2]
```
so afterwards 
`describe_1d` returns 
```python
IndexError: index 0 is out of bounds for axis 0 with size 0
```
as the series is empty. this is one line of code to fix, which is in the pull request.
as the original line returns a simple value of False, that leaves the Series empty because of how .loc works. this way the returned series cannot be empty.
> rare error fix

- README.md
`conda install pandas-profiling` command installs pandas-profiling from the conda-forge channel by default if it is added to the available channels. That version fails to import. At least for now let's specify the correct channel explicitly until the version in conda forge is synced and fixed.
> Updated Readme  "conda install"

- pandas_profiling/templates/base.html
This is fix for show "Correlations" section in result.
In report.py at line 207.
`render_htmls['correlations_html'] = correlations_html`
But, in base.html written '{{ correlation_html }}'
> correlation_html -> correlations_html

- README.md
- docs/index.html
Current code block recommends users to install from the anaconda channel, which currently hosts [version 1.4.1](https://anaconda.org/anaconda/pandas-profiling) of the package. Up-to-date version of the package is available on the [conda-forge](https://anaconda.org/conda-forge/pandas-profiling) channel.
> Recommend conda-forge channel instead of anaconda

- src/pandas_profiling/report/presentation/flavours/html/templates/wrapper/assets/style.css
Fix the UI issue that the columns of duplicate rows go outside container when there are many features.
Current columns are escaping the boundry:
After fix:
> ui: columns of duplicate rows

- docsrc/source/pages/advanced_usage.rst
The documentation has `configuration_file` listed as the parameter for `ProfileReport`, but the code actually uses `config_file`. This change updates the documentation to reflect the code.
> Correct ProfileReport config_file parameter documentation

- src/pandas_profiling/model/summary.py
- tests/issues/test_issue537.py
References issue #537 
Problem :
ValueError is raised when running ProfileReport on large datasets and with multiprocessing on (pool_size >1). This is likely due to the series.fillna(np.nan, inplace=True) in summary.py seems to be performing multiple in-place mutations to the underlying DataFrame object through the passed series reference, resulting in some kind of race condition where two of the processes try to write to the DataFrame at the same time and the ValueError then occurs. This is also why changing the pool_size to 1 fixes the issue, and why the error doesn't always occur - you probably need enough data and threads to hit the race condition.
Solution :
Replace series.fillna(np.nan, inplace=True) with series = series.fillna(np.nan) , negating any side effects from mutation. …
> fix #537  ValueError race condition when running multiprocessing with describe1d

- src/pandas_profiling/model/summary.py
- src/pandas_profiling/visualisation/plot.py
For a dataframe like:
A	B	C
0	1.0	7.0	NaN
1	2.0	8.0	NaN
2	3.0	9.0	NaN
3	4.0	NaN	13.0
4	5.0	NaN	14.0
5	6.0	NaN	15.0
6	NaN	10.0	16.0
7	NaN	11.0	17.0
8	NaN	12.0	18.0
the 'Interactions' tab would not display any data (as all rows contain NaN's) while any pair of columns would contain valid data to plot.
This change allows columns A, B, and C to be pairwise plotted against each other by only removing rows with NaN's between the pairwise columns.
> Update get_scatter_matrix for sparse dataframes

- src/pandas_profiling/profile_report.py
ProfileReport.to_json() exports some data using Pandas DataFrame and
without this fix they are encoded using str(), which doesn't give the
whole data.
> profile_report: use to_json() to encode pd.DataFrame to json

- tests/issues/test_issue537.py
There is a small typo in tests/issues/test_issue537.py.
Should read `summary` rather than `summmary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, summmary -> summary

- requirements-test.txt
- src/pandas_profiling/utils/dataframe.py
- tests/unit/test_utils.py
> Handle on the fly decompression of data files supported by pandas

- examples/features/great_expectations_example.py
- src/pandas_profiling/expectations_report.py
After some discussion with @spbail, we though it made sense to have just one `to_expectation_suite` method, with parameters for saving suites, running validations, and building data docs. We combined them and updated the examples to match.
> Consolidated the to_expectation_suite methods

- src/pandas_profiling/expectations_report.py
This is a workaround for a known issue: whenever you add expectations to a batch, the suite object that's part of the batch isn't actually modified in place. We're updating `suite` with the populated expectation suite from the batch before using it in the rest of the function.
> Fixing empty suite issue

- README.md
The current link is invalid and will not load when clicked on by a user. Removing the `<` should fix this issue.
> docs: Removing extra "<" from link in README.md

- requirements-test.txt
- tests/issues/test_issue147.py
The dependency to `fastparquet ` is not required anymore since `pyarrow` is available in python3.8 now.
Also see https://github.com/pandas-profiling/pandas-profiling/pull/670#issuecomment-786772204
> Reverted the fastparquet dependency replacement of pyarrow

- docsrc/source/pages/changelog/v2_12_0.rst
- requirements.txt
- setup.py
This will allow installing the package without installing all of Jupyter, if you only want HTML output.
There's a PR over at PhiK's repo to get rid of the numba/llvmlite hard dependency; an earlier revision of this PR also took care of making PhiK optional. https://github.com/KaveIO/PhiK/pull/17
> build: Move ipywidgets to extras

- requirements.txt
This drops the hard dependency on numba.
Follows up on #708
Refs KaveIO/PhiK#17
> build: Upgrade phik

- README.md
I've removed the dead link to the dark themed configuration file that no longer exists. 
Closes #734 
I tried to run make docs but I've struggled to create an environment that works in - I created an empty conda environment with Python 3.9 and pip then ran:
1. python setup.py install
2. pip install -r requirements-dev.txt
3. pip install -r requirements-test.txt
4. make docs
But make always errors out looking for README.md in the root packages dir. I'm more a conda package person so sorry if I'm doing anything dumb here.
> Removed dead link to dark theme config file

- .github/dependabot.yml
https://docs.github.com/en/code-security/supply-chain-security/upgrading-from-dependabotcom-to-github-native-dependabot
> ci: migrate dependabot

- docsrc/source/pages/advanced_usage.rst
- src/pandas_profiling/config.py
- tests/unit/test_config.py
Fixes Issue #785 by changing The parent class of `Settings` in config.py to `BaseModel`.
When running
```profile = ProfileReport(df)```
I get the following error
```
~/github/pandas-profiling/src/pandas_profiling/profile_report.py in __init__(self, df, minimal, explorative, sensitive, dark_mode, orange_mode, sample, config_file, lazy, typeset, summarizer, config, **kwargs)
78             raise ValueError("Can init a not-lazy ProfileReport with no DataFrame")
79
---> 80         report_config: Settings = Settings() if config is None else config
81
82         if config_file is not None and minimal:
~/.pyenv/versions/3.7.9/envs/pandas-profiling-debug/lib/python3.7/site-packages/pydantic/env_settings.cpython-37m-darwin.so in pydantic.env_settings.BaseSettings.__init__() …
```
> Bugfix: change Settings to child of BaseModel

- src/pandas_profiling/config.py
- src/pandas_profiling/config_default.yaml
- src/pandas_profiling/config_minimal.yaml
- src/pandas_profiling/model/pandas/describe_categorical_pandas.py
- tests/unit/test_pandas/test_describe_categorical_pandas.py
Stop words can be defined by changing the config of the ProfileReport:
-> profile.config.vars.cat.stop_words = [the, to]
The stop words are then ignored in the word count and frequency table : 
My changes have no impact on the character count and frequency table.
> ENH:  issue #863 If defined, stop words to be ignored in word count table 

- src/pandas_profiling/report/structure/report.py
PR related to issue #906 I raised a week ago.
This is a simple fix, that will not block the exectuion of the rendering. All types that are not in the render map are treated as unsupported and the HTML will only show a basic rendering.
> Quick fix for HTML rendering ith custom typeset

- setup.py
This was bumped in https://github.com/pandas-profiling/pandas-profiling/commit/3d6f9040eec2023caa1f5561772e67115d554666 at the time where the dep was `==`, a bit arbitrarily I guess.
Google Colab still uses jupyter-client 5.3.5, and it still works as far as I could test (ProfileReport)
> Losen jupyter-client dependency for Colab

- docsrc/source/pages/advanced_usage.rst
- src/pandas_profiling/config.py
- src/pandas_profiling/config_default.yaml
- src/pandas_profiling/config_minimal.yaml
- src/pandas_profiling/visualisation/plot.py
- tests/unit/test_visualizations.py
Allows for the colours of the pie chart to set to any matplotlib compatible colour string.
profile.config.plot.pie.colorscolors= ["gold", "b", "#FF796C"]
> Feature: Custom pie plot colors, fixes #571

- src/pandas_profiling/model/alerts.py
- src/pandas_profiling/report/structure/variables/render_real.py
Spark kurtosis and skewness functions changed
the output from np.nan to None, which caused
some errors. Using pd.isnull instead of np.isnan
enables the handling of both None and np.nan
better. Also make kurtosis and skewness fields
optional.
> fix: fix skewness and kurtosis errors

- src/pandas_profiling/model/spark/dataframe_spark.py
- src/pandas_profiling/model/spark/table_spark.py
- tests/backends/spark_backend/test_descriptions_spark.py
Enable maptypes to be ignored explicitly by spark so that profiling works properly
> feat: ignore maptypes and explicitly warn user

- docsrc/source/pages/great_expectations_integration.rst
The current URL link results in an `404 - File Not Found` error.
This is because the filename has a `.html` extension instead of `.py`.
However, just correcting the extension will make the file downloadable which is not the desired outcome. So I have changed the full path so that the example code opens in github like other source examples.
> docs: fix typo in link

- README.md
- docsrc/source/pages/examples.rst
This PR: 
- Removed outdated examples from the documentation
- Fixes links (Colab, Binder, to repo)
- Adjusts wording and organization of the examples (remove the _"Showcase specific features"_ section because almost all examples showcase specific features - handling different types of datasets of different sizes, for instance - and details can be added in the description)
- Syncs examples in the `README.md` with the documentation
@sbrugman This is my first time contributing, let me know if I am not doing things right or of any adjustments needed.
> Fix & clean examples in docs and README.md

- .github/ISSUE_TEMPLATE/bug_report_form.yaml
- .github/ISSUE_TEMPLATE/feature_request_form.yaml
- Makefile
- README.md
- docsrc/Makefile
- docsrc/make.bat
- docsrc/source/pages/announcements/2020-05-07-release-v2-7-0.rst
- docsrc/source/pages/announcements/2020-05-12-release-v2-8-0.rst
- docsrc/source/pages/changelog/v2_11_0.rst
- make.bat
- requirements-dev.txt
Sphinx with an RTD theme is the current documentation system. However, a pdoc3 -based documentation page is still up, although it's not being used. This branch deprecates it:
- Removes all `pdoc` related instructions from makefiles and similars.
- Updates links to documentation across the repo (from `docs/rtd/` to `/docs/`)
**Still missing:** 
- Set up redirect from `/docs/rtd` to `/docs/` (release CI/CD pipeline)
> Deprecate pdoc-based documentation page

- 404.html
What the title says: 404.html page which automatically redirects to the docs' home to handle all the changes in documentation structure and location currently in progress (`pdoc` deprecation, new internal and external structure)
> chore: add a 404 redirecting to documentation's home

- README.md
- docsrc/source/pages/getting_started/overview.rst
- docsrc/source/pages/integrations/cloud_services.rst
**This PR:**
- Simplifies the `README.md` structure and contents:
- Overview
- ▶️ Quickstart
- 👀 Examples
- 🛠️ Installation
- 📝 Use cases
- 🔗 Integrations
- 🙋 Support
- 🤝🏽 Contributing
- Brings content more in line with the updated documentation
- Tries to surface the most relevant content (lowering time-to-value of the page, particularly to newcomers) and defers everything else to the documentation (instead of including the content)
- Fixes a link to the Google Cloud Platform example using `pandas-profiling` in the docs (previous link was broken, resource was found on a notebook on GCP's GitHub)
As usual, in some aspects an opinionated take, so happy to rollback some of the changes after discussion.
A live version of the updated README.md [is available …
> Improvements to README.md

- src/pandas_profiling/model/alerts.py
- tests/issues/test_issue824.py
#824 
Problem : The alert is probably generated for each active correlation calculation
Solution : Field will be marked once is labelled as highly correlated for any calculation
1) Created Test case according to issue#824
2) Amended alerts.py check_correlation_alerts to create one alert once it is identified as highly correlated by a method
> Fixed #824: High correlation warning printed multiple times

- src/pandas_profiling/model/pandas/duplicates_pandas.py
Fixes #1012 
It is a bug with the pandas groupby (which is used to showcase examples of duplicated rows) that does not consider the missing values.
> fix: pandas groupby ignoring duplicates with nans

- src/pandas_profiling/config.py
- src/pandas_profiling/profile_report.py
Add a parameter to sort the data frame for time-series, the parameter is only used if the `tsmode` is active.
```python
profile = ProfileReport(df, tsmode=True, sortby="<column_name>")
```
> feat: add sortby parameter to timeseries mode

- src/pandas_profiling/model/pandas/describe_timeseries_pandas.py
- src/pandas_profiling/report/structure/variables/render_timeseries.py
add the statistic test for stationarity to the descriptive statistics tab
> feat: add augmented dickey fuller test to stat tab

- src/pandas_profiling/model/handler.py
- src/pandas_profiling/report/structure/variables/render_boolean.py
- src/pandas_profiling/report/structure/variables/render_categorical.py
- venv/spark.yml
After latest develop changes and a long time since the last merge with develop, the latest develop merge has killed the spark-branch. These are a bunch of minimal fixes to get it working again
Fix merge conflicts
Disabled boolean rendering [to be fixed later]
Disabled categorical rendering [to be fixed later]
Guide for building and testing spark-profiling can be found [here](https://github.com/ydataai/pandas-profiling/wiki)
> fix: get basic example working again

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Adding a `devcontainer` for VSCode and Codespaces. 
Fixed #987
See also: 
1. [GitHub CodeSpace devcontainers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers)
2. [VSCode devcontainers](https://code.visualstudio.com/docs/remote/create-dev-container)
> chore: add .devcontainer

- src/pandas_profiling/model/pandas/correlations_pandas.py
Fixes #1099.
Cramer's correlation fails when the contingency table between two columns is empty, this seems to be a frequent issue in cases where the columns have a high percentage of missing values.
> fix: cramer's correlation fails with missing values

- README.md
- docsrc/source/pages/getting_started/installation.rst
- requirements.txt
- setup.py
- src/pandas_profiling/model/pandas/describe_categorical_pandas.py
Knowing the exact Unicode properties is likely not a priority for all users. Furthermore, unicodedata as of Python 3.10 is based on UCD 13, so the category data in there ought to be fairly recent.
This should probably be documented (as well as the `[unicode]` extra), but I'm not sure what the best place for it would be.
Refs https://github.com/dylan-profiler/tangled-up-in-unicode/issues/10 – importing `tangled` will create 2 gigabytes of 
bytecode files and takes a while.
> fix: make tangled-up-in-unicode an optional dependency

- src/pandas_profiling/model/correlations.py
- src/pandas_profiling/model/pandas/correlations_pandas.py
Fix "Auto" correlation requiring extra configuration parameter `n_bins` which was already available through settings.
> fix: correlation `auto` passing extra parameters

- src/pandas_profiling/model/pandas/summary_pandas.py
- tests/issues/test_issue537.py
... in 1.5.0 (sep 2022), items() available since 0.25 (july 2019)
> fix: pandas.DataFrame.iteritems() deprecated

- src/pandas_profiling/profile_report.py
- src/pandas_profiling/report/presentation/flavours/html/templates/alerts.html
- src/pandas_profiling/report/presentation/flavours/html/templates/table.html
- src/pandas_profiling/report/presentation/flavours/html/templates/wrapper/assets/style.css
- src/pandas_profiling/report/structure/variables/render_timeseries.py
- src/pandas_profiling/visualisation/plot.py
- tests/unit/test_comparison.py
Fixed some bugs (most likely caused by refactoring) and added support to time series comparison
> fix: comparison bugs

- src/pandas_profiling/visualisation/context.py
The following script consistently fails when the multi-threading option is active, entering an infinity loop triggered by matplotlib backend. The fix consists in temporarily changing the backend while creating the plots (ty @fabclmnt for the help with this one).
```python
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
def create_dataframes(size=1000, alt=False):
size = size if not alt else size * 2
time_steps = np.arange(size)
df1 =  pd.DataFrame(
{
"sin": map(lambda x: round(np.sin(x * np.pi / 180), 2), time_steps),
"gaussian": map(lambda x: round(x, 2), np.random.normal(0, 1, size)),
}
)
df2 = pd.DataFrame(
{
"sin": map(lambda x: round(np.sin(x * np.pi / 180), 2), time_steps),
"miss2": np.random.choice([0, 1, 2, 3, np.nan], replace=True, size=size),
} …
```
> fix: multi thread error on matplotlib default backend

- src/pandas_profiling/model/pandas/correlations_pandas.py
- tests/issues/test_issue51.py
Pandas profiling returns correlations for constant columns with every other column when calculating 'Auto' and 'Cramers'. This PR ensures these correlations are not calculated.
> fix: remove correlation calculation for constants

- examples/features/correlation_auto_example.py
- src/pandas_profiling/config_default.yaml
The Auto correlation matrix calculation should be enabled by default, with the other correlation matrices disabled. 
The example file for this feature has been updated to show:
- How to disable the 'auto' correlation matrix calculation.
- How to update the n_bins setting.
- How to enable the calculation of other correlation matrices.
> fix: update config files to only calculate 'auto' correlation

- .github/semantic.yml
- .github/workflows/merge-master.yml
- .github/workflows/pull-request.yml
- src/pandas_profiling/utils/cache.py
`requests` doesn't seem to handle TLS/SSL pretty well. It returns `Forbidden` when we try to get a content from an HTTPS URL such as `https://query1.finance.yahoo.com/v7/finance/download/BABA?period1=1635724800&period2=1667260800&interval=1d&events=history&includeAdjustedClose=true`. That's why we should use `urllib.request` instead.
On the other hand, I need to remove `raise FileNotFoundError("Could not download resource")` as `urllib.request.urlopen` already handle that with its `HTTPError`.
> fix(utils): use 'urllib.request' instead of 'requests'

- examples/features/correlation_demo.py
- src/pandas_profiling/config.py
At the moment auto correlation is the only correlation calculated when specifying config_default.yaml. This fix ensures that the auto correlation is also only calculated when no configuration file is specified.
After these changes the reports appear as the following:
```
profile = ProfileReport(
df,
title="Profile Report of the UCI Bank Marketing Dataset",
)
```
```
no_auto_profile = ProfileReport(
df,
title="Profile Report of the UCI Bank Marketing Dataset",
correlations={
"auto": {"calculate": False},
"pearson": {"calculate": True},
"cramers": {"calculate": True},
},
)
```
```
profile = ProfileReport(
df,
title="Profile Report of the UCI Bank Marketing Dataset",
config_file="src/pandas_profiling/config_default.yaml",
correlations={
"auto": {"n_bins": 8},
},
)
```
```
no_auto_profile = …
```
> fix: only compute auto correlation when no config is specified

- src/pandas_profiling/visualisation/plot.py
- tests/unit/test_plot.py
When using the flag `sensitive=True`, the Common Values plot was still displaying the legends with all the categories (for both bar and pie charts). The legends are now hidden when this flag is active (see the images below). The unit tests were updated to cover the new code changes. All unit tests passed.
> fix: categorical data not being obscured in the common values plot

- src/pandas_profiling/compare_reports.py
- src/pandas_profiling/profile_report.py
Until now it was not possible to specify the configuration to use for the comparison report and it would use the default one which my not be suitable (e.g. if values needs to be hidden).
Build a report with a particular configuration (no nav bar)
Compare to a second report: by default is now as the same config as the original report:
But if I want my comparison report to have a particular config, I can specify it (in this case, the nav bar is back):
> feat: allow to specify the configuration for the comparison report

- src/pandas_profiling/report/formatters.py
- tests/issues/test_issue215.py
A percentage might be higher than 100% when it expresses a ratio for instance.
We should not control this behavior at the formatter level.
> fix: do no raise exception for percentage formatter

- src/pandas_profiling/config.py
- src/pandas_profiling/report/formatters.py
- src/pandas_profiling/report/presentation/core/__init__.py
- src/pandas_profiling/report/presentation/core/correlation_table.py
- src/pandas_profiling/report/presentation/flavours/flavours.py
- src/pandas_profiling/report/presentation/flavours/html/__init__.py
- src/pandas_profiling/report/presentation/flavours/html/correlation_table.py
- src/pandas_profiling/report/presentation/flavours/html/templates/correlation_table.html
- src/pandas_profiling/report/presentation/flavours/html/templates/wrapper/assets/style.css
- src/pandas_profiling/report/presentation/flavours/widget/__init__.py
- src/pandas_profiling/report/presentation/flavours/widget/correlation_table.py
- src/pandas_profiling/report/structure/correlations.py
- src/pandas_profiling/report/structure/overview.py
- tests/issues/test_issue215.py
- tests/unit/test_correlations.py
- For each correlation, we now have the option to display the data as a heatmap and as a table (see the 2 images below). By default, both visualizations are displayed. To only show the heatmaps, set `correlation_table=False`.
- This feature was also added to the compare reports (see the 2 images below).
- New unit tests were added to the correlation rendering components. All unit tests passed.
> feat: add heatmap values as a table under correlations

- docsrc/source/pages/getting_started/overview.rst
- docsrc/source/pages/tables/config_variables.csv
- docsrc/source/pages/tables/data_quality_alerts.csv
- src/pandas_profiling/config.py
- src/pandas_profiling/model/alerts.py
- src/pandas_profiling/model/pandas/describe_boolean_pandas.py
- src/pandas_profiling/model/pandas/describe_categorical_pandas.py
- src/pandas_profiling/model/pandas/imbalance_pandas.py
- src/pandas_profiling/model/summarizer.py
- src/pandas_profiling/report/presentation/flavours/html/alerts.py
- src/pandas_profiling/report/presentation/flavours/html/templates/alerts/alert_imbalance.html
- src/pandas_profiling/report/presentation/flavours/widget/alerts.py
- tests/unit/test_correlations.py
- tests/unit/test_example.py
- tests/unit/test_pandas/test_imbalance.py
**Context**
Users may want to assess how balanced their Categorical and Boolean columns are and be warned if there are signs of high imbalance. This becomes increasingly difficult for them to manually interpret with a higher number of classes (for Categorical Variables). 
**Solution**
This PR aims to introduce an elegant and interpretable score which can be used to alert the user of high imbalance in their categorical or Boolean variables.
The changes to the report:
(alerts)
**The Maths**
The class balance score for categorical and boolean variables uses entropy to calculate a  bounded score between 0 and 1. A perfectly uniform distribution would return a score of 0, and a perfectly imbalanced distribution would return a score of 1.
When dealing with probabilities with finite values (e.g …
> feat: implement imbalanced warning

- src/pandas_profiling/config.py
- src/pandas_profiling/report/structure/report.py
fix a bug where disabling duplicates leads to the comparison report trying to render an inexistent data frame
> fix: comparison fails when duplicates are disable

- src/pandas_profiling/compare_reports.py
When one of the ProfileReports where already pre-computed (either using lazy=False, persisting the report, or anything that triggers profile.get_description()) could cause errors when the profiles were created using a different configuration. This lead to errors when comparing sessions (e.g. duplicates) of the report that were disabled in only one of the reports.
Added a parameter to enforce the reports to be computed with the same configuration. 
This parameter is only necessary when at least ProfileReport was already calculated and the ProfileReports have different settings.
e.g. 
```python
p1 = ProfileReport(data)
p2 = ProfileReport(data, lazy=False, minimal=True)
p1.compare(p2, compute=True)
```
> fix: error comparing reports with pre-computed description_set

- src/pandas_profiling/report/presentation/flavours/html/templates/wrapper/assets/style.css
remove from `style.css` code was designed to display the frequency table horizontally instead of vertically:
old:
new:
> fix: cat frequency var plot

- src/pandas_profiling/visualisation/plot.py
It was hard to compare the histograms without an explicit scale, so the histograms were change to display it in the same plot
> fix: comparison histogram

- src/pandas_profiling/compare_reports.py
- src/pandas_profiling/model/alerts.py
- src/pandas_profiling/report/presentation/flavours/html/templates/alerts.html
Fix the error: 
```jinja2.exceptions.UndefinedError: 'None' has no attribute 'alert_type'```
This error is triggered when comparing datasets that don't have the same set of alerts.
> fix: comparison alerts

- src/pandas_profiling/model/describe.py
- src/pandas_profiling/model/pandas/correlations_pandas.py
The `Auto` correlation and the interaction plots filter the numeric variables prior to creating the plots, this was filtering out the TimeSeries vars, which are also numeric.
> fix: time series vars being excluded from correlation and  interaction plots

- src/ydata_profiling/model/pandas/correlations_pandas.py
Fixes an error when calculating the correlation between columns where there is no nonnull simultaneously for both columns, i.e.
when column A is non-null column B is null and vice versa.
> fix: correlation between columns w/o non-null row

- src/ydata_profiling/compare_reports.py
- src/ydata_profiling/model/pandas/summary_pandas.py
- src/ydata_profiling/model/typeset.py
- src/ydata_profiling/profile_report.py
- tests/unit/test_typeset_default.py
Add a feature enabling users to define the variable types using `type_schema`, a simple dictionary with column_name: type pairs. The columns not defined in the type_schema will follow the usual type inference flow.
```python
def create_dataframe(size=1000, alt=False):
time_steps = np.arange(size)
return pd.DataFrame(
{
"ascending_sequence": time_steps,
"sin": map(lambda x: round(np.sin(x * np.pi / 180), 2), time_steps),
"cos": map(lambda x: round(np.cos(x * np.pi / 180), 2), time_steps),
"cat": np.random.choice([0,1,2], size=size, replace=True),
}
)
df = create_dataframe()
prof = ProfileReport(
df,
tsmode=True,
type_schema={
"ascending_sequence": "categorical",
"sin": "timeseries",
"cos": "numeric",
"cat": "numeric",
})
prof.to_file("profile.html")
```
> feat: add type schema

- src/ydata_profiling/compare_reports.py
- src/ydata_profiling/profile_report.py
- tests/unit/test_comparison.py
This PR solves two issues:
- When PySpark is installed, the ProfileReport was not prepared to be instantiated without a DataFrame. This only worked when PySpark was not installed because the `sDataFrame` `TypeVar` assumed None when the PySpark DataFrame import failed. The ProfileReport can now be instantiated without DataFrames in both scenarios.
- The comparison between reports failed when the summary of the reports (obtained through the `get_description` method) was used. The validations and preprocessing steps of the `compare` method were not prepared to work with these summaries, and the code assumed only ProfileReport objects were used. The comparison now works with both ProfileReport objects and report summaries (i.e., dictionaries).
> fix: comparing issues when pyspark is installed and when the report summaries are used

- src/ydata_profiling/model/alerts.py
- src/ydata_profiling/model/summarizer.py
- src/ydata_profiling/profile_report.py
Fixed an issue where render_json ignores the redact configuration (i.e. sensitive parameter of ProfileReport). Now the resulting json replaces the values by `READCTED_#`.
e.g.
```
{
...
"variables": {
"text_var": {
...
"value_counts_without_nan": {
"REDACTED_0": 2,
"REDACTED_1": 2,
...
}
"word_counts": {
"REDACTED_0": 358,
"REDACTED_1": 326,
...
}
},
}
```
fixes https://github.com/ydataai/ydata-profiling/issues/1300
> fix: json ignoring redact

- src/ydata_profiling/model/alerts.py
Add to render_json the same information available in the HTML for alerts.
previously:
```
"alerts": [
"[HIGH_CORRELATION] alert on column ascending_sequence",
"[HIGH_CORRELATION] alert on column descending_sequence_with_noise",
"[ZEROS] alert on column zeros"
]
```
now:
```
"alerts": [
"[ascending_sequence] is highly overall correlated with [descending_sequence_with_noise]",
"[descending_sequence_with_noise] is highly overall correlated with [ascending_sequence]",
"[zeros] has 1000 (100.0%) zeros"
],
```
Fixes https://github.com/ydataai/ydata-profiling/issues/1301
> fix: complete alerts information in json

- src/ydata_profiling/model/typeset.py
- tests/unit/test_time_series.py
Drop the time dependence check for time series type inference
> fix: infer all `Numeric` vars as `TimeSeries` when tsmode=True

- src/ydata_profiling/model/typeset.py
- tests/unit/test_time_series.py
Reverts ydataai/ydata-profiling#1343
> fix: revert "infer all `Numeric` vars as `TimeSeries` when tsmode=True"

- src/ydata_profiling/report/presentation/flavours/html/templates/variable_info.html
The alerts for a variable with a single alert were not displayed in the variables section.
> fix: alert not shown for vars with a single alert

- src/ydata_profiling/report/structure/variables/render_categorical.py
- src/ydata_profiling/report/structure/variables/render_text.py
fixes https://github.com/ydataai/ydata-profiling/issues/1377
Handles text variables as categoricals if sensitive is true. Here is an example of a column with random text:
sensitivity = False:
sensitivity = True
> fix: handle text as categoricals if sensitive=True

- src/ydata_profiling/model/pandas/describe_timeseries_pandas.py
- src/ydata_profiling/model/pandas/timeseries_index_pandas.py
- src/ydata_profiling/model/pandas/utils_pandas.py
- src/ydata_profiling/report/structure/variables/render_timeseries.py
- src/ydata_profiling/visualisation/plot.py
Adds a gap analysis tab to time series variables indicating the gaps in the series
> feat: fist version of the gap analysis tab for ts

- src/ydata_profiling/model/pandas/describe_timeseries_pandas.py
- src/ydata_profiling/report/structure/overview.py
- src/ydata_profiling/report/structure/variables/render_timeseries.py
- src/ydata_profiling/visualisation/plot.py
fixes:
- scaled tab scaling only for the comparison report
- legend overlapping and hiding part of the plot
- added some to help with the visualization of multiple series (bear in mind that as the number of series increases harder it is to have a comprehensive visualization with all the series)
- removed period and frequency from the gap analysis table since it is constant for all variables and it is available at the time index tab
- added some tolerance for gap identification to avoid false positives
> fix: time index and gap analysis bugs

- src/ydata_profiling/model/pandas/duplicates_pandas.py
Fixing Bug Report #1384
Dataset with categorical features causes memory error even on tiny dataset.
> fix: update duplicates_pandas.py

- src/ydata_profiling/report/presentation/flavours/html/templates/wrapper/javascript.html
- src/ydata_profiling/report/presentation/flavours/html/templates/wrapper/style.html
When inline is set to FALSE and the report is exported as an html file, {{ file_name }} would render as an empty string and the paths to both the stylesheets and the scripts would be incorrect, causing visualization issues. 
To fix this, the (( file_name }} clause was replaced with {{ assets_prefix }}, which correctly points to the referenced stylesheets and js scripts.
> fix: {{ file_name }} error in HTML wrapper

- src/ydata_profiling/config.py
- src/ydata_profiling/model/summary_algorithms.py
- tests/unit/test_summary_algos.py
- Add an option to the histogram config to enable using numpy density parameter
- minor refactoring to avoid computing histogram twice
- add a minimal unity test for histogram_compute
closes https://github.com/ydataai/ydata-profiling/issues/1356
> feat: add density histogram

- src/ydata_profiling/profile_report.py
Fix bug when creating a new report.
Caused by the `@typechecked` decorator on the `ProfileReport` class, and missing the `Optional[]` typehint on the `config_file` parameter.
Resolves #1439
> fix: bug when creating a new report

- src/ydata_profiling/report/presentation/flavours/html/templates/table.html
- tests/unit/test_time_series.py
closes https://github.com/ydataai/ydata-profiling/issues/1437
Update the table template to use the string in its original format without overflowing.
> fix: table template ignoring text format

- docs/advanced_settings/tables/config_general.csv
- docs/features/big_data.md
- docs/features/sensitive_data.md
Update pandas-profiling to ydata-profiling in some forgotten places in docs.
> docs: fix hyperlink - related to package name change

- mkdocs.yml
- src/ydata_profiling/model/pandas/correlations_pandas.py
Sort heatmap columns for correlations `Auto` and `cramer's` to ensure a deterministic order for profiling comparison
> fix: use deterministic column order for correlations heatmap

- src/ydata_profiling/profile_report.py
Added code to prompt users who have Pillow version <9.5.0 as WordCloud throws errors for versions below it. This does not change the functionality in the code but enhances it.
> feat: Modified code to warn users to update Pillow version 

- src/ydata_profiling/profile_report.py
- tests/issues/test_issue1529.py
closes issue #[1529](https://github.com/ydataai/ydata-profiling/issues/1529)
> fix: comparison to_json pd.Series encoding error

- src/ydata_profiling/expectations_report.py
based on #1504 switch create_expectation_suite with add_expectation_suite.
This aligns with the changes in https://github.com/great-expectations/great_expectations/pull/7117
> fix: switch create_expectation_suite with add

- src/ydata_profiling/expectations_report.py
- src/ydata_profiling/model/pandas/describe_timeseries_pandas.py
- src/ydata_profiling/report/structure/overview.py
- src/ydata_profiling/report/structure/variables/render_timeseries.py
When calculating gap statistics for date indexes, when there were no gaps the gap_stats.min() returned a NaT which lead to failures while trying to render it.
Also fixed a small error on time series statistics overview tab
> fix: timeseries gap comparison failing with no gaps for date index

- src/ydata_profiling/utils/cache.py
- tests/unit/test_ge_integration.py
Fix great expectations unit tests after changes in https://github.com/ydataai/ydata-profiling/pull/1540
> fix: great expectations unit tests referring to deprecated method

- src/ydata_profiling/model/pandas/describe_boolean_pandas.py
- src/ydata_profiling/model/pandas/describe_categorical_pandas.py
- src/ydata_profiling/model/pandas/describe_date_pandas.py
- src/ydata_profiling/model/summary_algorithms.py
- src/ydata_profiling/report/structure/variables/render_date.py
Avoid error thrown when empty column is set as categorical with the _type_schema_
> fix: zero division for categorical colums with 100% missing data

- requirements.txt
Seaborn 0.13 fixes an issue with annotating heatmaps and I'd like to be able to use ydata-profiling in a repository that needs this fix.
I checked git blame and didn't see a reason for the upper-bound pin. I tested on 0.13.2 with Python 3.10 and all unit tests passed.
> chore(deps): remove seaborn upper limit

- README.md
See python3statement/python3statement.github.io#292.
To avoid having to pay for the domain indefinitely the maintainers are now redirecting to GitHub Pages.
> chore: update python3statement url

- src/ydata_profiling/report/presentation/flavours/html/templates/alerts/alert_constant.html
As part of #1132, the calculation of `summary["mode"]` was removed ([here](https://github.com/ydataai/ydata-profiling/pull/1132/commits/ec976c8a786fc2a563f2fa080d80c1b70494655a)). However, the template still refers to this value and results in a less helpful error message as below:
This PR changes the template so that the correct value is used:
> fix: Use correct value in ConstantAlert template

- src/ydata_profiling/model/spark/summary_spark.py
#1476 
In the Spark version, the program will add some auxiliary columns to the dataframe during runtime, such as Count, Std, etc. 
If the original data to be analyzed already contains these columns, it may result in column name conflicts.
solution:
Before the program analysis, add the suffix "_customer" to all columns of the DataFrame. 
Remove the suffix when displaying the results.
> fix: Resolve the issue of conflicts between columns added during the analysis process and the original data columns in the Spark version.

- src/ydata_profiling/expectations_report.py
- tests/unit/test_ge_integration.py
Fix https://github.com/ydataai/ydata-profiling/pull/1540 remove keyword argument 'overwrite_existing'.
This aligns with the changes made in https://github.com/great-expectations/great_expectations/pull/7117, great_expectations/data_context/data_context/abstract_data_context.py
> fix: 1540 add_expectation_suite doesn't have key overwrite_existing

- src/ydata_profiling/visualisation/plot.py
- tests/unit/test_plot.py
`timeseries_heatmap` from `ydata_profiling.visualisation.plot` drops an error, when 'entity_column' is of type str.
The reason for this is that the arguments to `pivot_table` are passed in the wrong order - see [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot_table.html). 
Existing unit test does not cover a case where entities are strings, thus the bug was missed.
> fix: timeseries_heatmap

- src/ydata_profiling/config.py
- src/ydata_profiling/config_default.yaml
- src/ydata_profiling/config_minimal.yaml
- src/ydata_profiling/visualisation/plot.py
This PR is a proposed solution to issue #1466.
The default font in Wordcloud is `DruidSansMono.ttf`, and if the languages ​​of the values ​​are different, the image may be broken.
* Example data (language: korean)
This is a known solution when using wordcloud, but the problem could not be solved because the 'font_path' argument was not specified in ydata_profiling.
I added a setting variable to 'Settings.plot' to pass the value to the font_path argument of word cloud.
Actually, I'm not sure if it's appropriate to put it here.
I just thought that it was a variable for wordcloud plot rendering, and the criterion for judgment was that I thought it could be used in other matplotlib plots as well.
If you do the following, you can check that the wordcloud is displayed normally.
``` …
```
> feat: Add font_path arg for wordcloud

- tests/unit/test_pandas/test_correlations.py
This PR removes the warning:
```
tests/unit/test_pandas/test_correlations.py::test_numeric_auto_equals_spearman
/home/runner/work/ydata-profiling/ydata-profiling/tests/unit/test_pandas/test_correlations.py:69: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
assert auto_result.iloc[0][1] == pytest.approx(spearman_result.iloc[0][1], 0.01)
tests/unit/test_pandas/test_correlations.py::test_categorical_auto_equals_equals_cramers
/home/runner/work/ydata-profiling/ydata-profiling/tests/unit/test_pandas/test_correlations.py:83: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future …
```
> feat: remove warning while using pandas iloc in the test files

- src/ydata_profiling/compare_reports.py
Comparison report type enforcement was only working when both profiles were not pre-computed. When the reference profile had  columns that were not present in the compared profile, it was leading to errors in the type inference step.
> fix: remove compare report type enforcement

- src/ydata_profiling/model/pandas/describe_numeric_pandas.py
Correction for the error:
`AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.`
> fix: Correction for numpy.NaN deprecating to numpy.nan

- src/ydata_profiling/config.py
- src/ydata_profiling/model/pandas/describe_timeseries_pandas.py
Add `autolag` and `maxlag` parameters to config. These parameters can be added to the profiling configuration file under the timeseries vars:
```
vars:
timeseries:
autolag: AIC
maxlag: 30
significance: 0.05
```
closes https://github.com/ydataai/ydata-profiling/issues/1639
> feat: add adfuller stationary test parameters to config

- src/ydata_profiling/profile_report.py
- src/ydata_profiling/utils/common.py
- src/ydata_profiling/utils/logger.py
> chore: update metrics validation

- src/ydata_profiling/model/pandas/describe_date_pandas.py
- src/ydata_profiling/model/pandas/summary_pandas.py
- src/ydata_profiling/model/typeset_relations.py
- src/ydata_profiling/report/structure/variables/render_date.py
- tests/unit/test_describe.py
Fixes conversion errors for DateTime types, when receiving unsupported dates (e.g. '0001-01-01').
With this fix the the invalid dates will be ignored when calculating the metrics that depend on the datetime types, while others (e.g. distinct values) will consider the date without any transformation.
It will also display the amount of invalid values identified
> fix: typeset invalid dates errors

- src/ydata_profiling/model/alerts.py
- src/ydata_profiling/model/pandas/summary_pandas.py
- src/ydata_profiling/report/structure/variables/render_generic.py
- tests/unit/test_typeset_default.py
Type schema did not check for empty columns leading to errors when trying to calculate some metrics over it. Also updates the type of an unsupported column when the type was defined by the user.
e.g. for columns:
```python
df = pd.DataFrame({
'date': ['0001-01-01', '9999-12-31', '2012-10-03', '2017-10-03', '2022-10-03', '2022-10-04'],
'null': [None]*6,
})
```
> fix: type schema not checking for empty columns

- requirements.txt
- setup.py
- src/ydata_profiling/__init__.py
The dependency on visions package is leading to an error whenever numba installed version is >=0.59. 
To support python 3.12, numba version is required to be at least 0.59.
> fix: add numba as a flavour to avoid errors related with deprecated methods due to dependencies

- src/ydata_profiling/model/pandas/duplicates_pandas.py
- tests/unit/test_index_column_name_clash.py
Previously, report generation failed for DataFrames where an index level had the same name as a column, resulting in a "ValueError: 'foo' is both an index level and a column label, which is ambiguous." This update removes index names for the relevant groupby operation, ensuring the column is prioritized.
> fix: Avoid failure when index level shares name with a column

- src/ydata_profiling/model/pandas/dataframe_pandas.py
- tests/unit/test_multiindex_columns.py
Previously, report generation failed for DataFrames with a MultiIndex on the column axis due to a "TypeError: Setting a MultiIndex dtype to anything other than object is not supported."
This update converts all indexes to their string representation: simple indexes remain unchanged, while MultiIndexes are represented in a tuple-style format.
> fix: convert multiIndex columns to string representation

- .github/workflows/release.yml
Fix the pipeline error 
Error: Trusted publishing exchange failure: 
OpenID Connect token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset
Link: https://github.com/ydataai/ydata-profiling/actions/runs/13933637673/job/38996679548
> chore: add permissions to the release file

- tests/issues/test_issue537.py
- tests/unit/test_report_options.py
- tests/unit/test_time_series.py
Adding new unit tests to improve test coverage:
- Time-series profiling reports
- Profiling report configurations
> chore: add more unit tests for better code coverage
