.travis.yml, README.md, appveyor.yml, appveyor_install.ps1
Add CI tests see https://travis-ci.org/nparley/pandas-profiling and https://ci.appveyor.com/project/nparley/pandas-profiling for test builds
=> Add CI tests

pandas_profiling/__init__.py
Thanks for this great tool! This fixes a small error.
The method did not correctly close files if errors occurred. Hope it helps.
=> added a with statement to savely write the output

pandas_profiling/templates.py
Small correction on the closing tag from `</l>` to `</li>`.
=> correction to <li> tag

pandas_profiling/base.py, pandas_profiling/templates.py, pandas_profiling/templates/mini_freq_table.html, pandas_profiling/templates/overview.html, pandas_profiling/templates/row_bool.html, pandas_profiling/tests.py
As highlighted in the issue #25, boolean variables are not correctly handled.
So, I've implemented a **new Boolean variable type**.
The implementation is close the categorical variable type, but I think it's useful to make the distinction between the two. For example, the **mean** stats is computed for boolean variables because it makes sense.
=> Implementation of a new Boolean variable type

pandas_profiling/templates.py
- added bootstrap labels for Skewed and Zeros
=> Fix #63: added Skewed and Zeros labels

pandas_profiling/__init__.py, pandas_profiling/base.py, pandas_profiling/describe.py, pandas_profiling/formatters.py, pandas_profiling/plot.py, pandas_profiling/report.py, pandas_profiling/templates.py, pandas_profiling/tests.py
Hey,
I have made a first big refactoring.There is still work to be done, but I would like to merge this structure as soon as possible in order to share this new code organization. 
I think nothing is broken, I've run successfully unit tests and personal tests in Jupyter notebooks.
Any feedback will be appreciated.
Best.
=> #65 Refactoring first step

pandas_profiling/describe.py
this minor tweak should fix [issue #106](https://github.com/pandas-profiling/pandas-profiling/issues/106) for python 2.7
Also fixes pct errors for unique, infinite, and zero
=> fixed issue #106 (Percentage of missing value inconsistent)

pandas_profiling/describe.py
I've solved issue #131 
The problem "bins" option was not reflected in the resulting histogram.
=> Fixed a bug bins option is not reflected in result histogram by

README.md
Hello,
Thank you for this awesome project! I was working through the docs today, and hit something in the README. The examples use `pd.read_csv()` to read in a CSV, but as far as I can tell this is not necessary to provide an example for users to try out `pandas-profiling`.
I hope you will consider this PR to change the README so the examples can be run just by copying and pasting the code. I think this will lead to a slightly better user experience for first-time visitors to the project.
-James
=> updated README example

.travis.yml
- This PR fixes #90 
- A much simpler Travis CI config file that builds across multiple python versions.
- Tests are not in a passing state therefore builds on travis-ci.org will fail. We need to work together to prioritize this quickly.
- Travis-ci.org is not yet set up as a GitHub integration. I either need to be added to the organization as an admin to finish the Travis set up or I need one of you (@romainx @JosPolfliet ) to follow step 1 (I've done the rest): https://travis-ci.com/getting_started
- You can see sample results on my Travis account here: https://travis-ci.org/Aylr/pandas-profiling
=> Travis CI set up

pandas_profiling/model/messages.py
=> Simple typo fix

pandas_profiling/utils/paths.py
fix return type to pass `mypy` static type checker
=> fix return type

.travis.yml, requirements-test.txt, requirements.txt
Extend Travis testing to also run `black` for code style
=> Test plugins

pandas_profiling/__init__.py
This feature is useful for using a custom config file to overwrite all or parts of the default configuration without the need to change the code and pass the settings as kwargs.
=> feat: add option to overwrite default with custom config file

requirements.txt
=> Require minimum jinja2 version

pandas_profiling/__init__.py, pandas_profiling/controller/console.py, pandas_profiling/model/correlations.py, pandas_profiling/model/messages.py
Resolve typing errors; includes fix for #274
=> Resolve typing errors

src/pandas_profiling/__init__.py
Also __from pandas_profiling.model.messages import MessageType__ for the _undefined name_ in the same method.
=> Undefined name: Don't forget self in get_rejected_variables()

Makefile, make.bat, src/pandas_profiling/__init__.py, src/pandas_profiling/utils/dataframe.py, tests/issues/test_issue243.py, tests/issues/test_issue249.py, tests/issues/test_issue_249.py, tests/unit/test_example.py
(and updates for makefiles)
Thank you @marco-cardoso and @tobycheese for your work :)
=> Tests and fixes for issue #243 and #249

src/pandas_profiling/model/base.py, tests/issues/test_issue351.py, tests/unit/test_describe.py
(rebased from progress_bar to master)
=> Fix and test for issue #351

src/pandas_profiling/visualisation/plot.py
Scale the font size of the labels in the correlation plot to the number of labels.
=> Correlation plot font sizes

src/pandas_profiling/config.py
=> Workaround for issue 214

src/pandas_profiling/__init__.py, tests/conftest.py, tests/issues/test_issue416.py, tests/unit/test_describe.py
Fix for issue #416:
- Introduce platform-specific markers in pytest
- Encode pandas Series as dict
- Include test for issue 416
=> Fix for issue #416 (infinite loop in Json Encode)

src/pandas_profiling/__init__.py, tests/issues/test_issue388.py
=> Helpful feedback when profile report extension is not supported.

docsrc/source/pages/integrations.rst
As suggested in https://github.com/Ghasel/streamlit-pandas-profiling/issues/2, here is an doc update on Pandas Profiling integration in Streamlit.
=> Update Streamlit integration

docsrc/source/pages/metadata.rst
=> Metadata docs

src/pandas_profiling/model/base.py, tests/issues/test_issue587.py
=> Fix check for infinite values

.pre-commit-config.yaml, examples/meteorites/meteorites.ipynb, examples/tutorials/modify_report_structure.ipynb, tests/notebooks/meteorites.ipynb
Hi :wave:
I've noticed that in your `.pre-commit-config.yaml` file, you run the `black` formatter on your Python source code but not on your Jupyter Notebooks.
So here's a little PR to add that
=> pre-commit: run black formatter on notebooks as well

README.md
- Update style for consistency across the doc and markdown best practices, like double stars for bold and single space for italics and spaces over tabs.
- Update code blocks and backticks for improved readability of markdown and the result
- Fixed numbering and spacing for a bullet list
Hope this is helpful 👍 Thanks.
=> Docs: Update README with improvements

.pre-commit-config.yaml, examples/meteorites/meteorites.ipynb, examples/tutorials/modify_report_structure.ipynb, requirements-dev.txt, src/pandas_profiling/config.py, src/pandas_profiling/model/base.py, src/pandas_profiling/model/messages.py, src/pandas_profiling/model/sample.py, src/pandas_profiling/profile_report.py, src/pandas_profiling/report/formatters.py, src/pandas_profiling/report/presentation/flavours/widget/warnings.py, src/pandas_profiling/report/structure/report.py, src/pandas_profiling/serialize_report.py, src/pandas_profiling/visualisation/plot.py, tests/conftest.py, tests/notebooks/meteorites.ipynb, tests/performance/timings.py, tests/unit/test_describe.py, tests/unit/test_renderable.py
- extend nbqa usage
- bump check-manifest
=> Update linting using pre-commit

docsrc/source/pages/support.rst
Added `mamba` troubleshooting tip from #655  to the support faq doc.
=> doc: added #655 to support faq

README.md, src/pandas_profiling/config_default.yaml, src/pandas_profiling/config_minimal.yaml, src/pandas_profiling/controller/console.py, src/pandas_profiling/model/summary.py, src/pandas_profiling/profile_report.py, src/pandas_profiling/serialize_report.py, tests/issues/test_issue51.py, tests/issues/test_issue72.py, tests/unit/test_serialize.py
Supersedes https://github.com/pandas-profiling/pandas-profiling/pull/680
=> Detect dtype from pandas df

docsrc/source/pages/great_expectations_integration.rst
Needs some tweaks once we've settled on the final method definition and expectation types! Also needs an explanation for the handler, would be good to get an example from @sbrugman for that!
=> [WIP] Adding documentation for Great Expectations integration

docsrc/source/pages/great_expectations_integration.rst, src/pandas_profiling/model/expectation_algorithms.py
These expectations seemed straightforward, so I added them to the expectation_algorithms.
=> Added expect_column_values_to_be_between for numeric and datetime columns.

docsrc/source/pages/great_expectations_integration.rst, src/pandas_profiling/expectations_report.py, tests/unit/test_ge_integration.py
test: extend and clean up (more atomic, higher coverage)
docs: add handler details
=> enhance: prevent double save_suite calls

README.md, docsrc/source/index.rst, docsrc/source/pages/great_expectations_integration.rst, examples/features/great_expectations_example.py, src/pandas_profiling/expectations_report.py, src/pandas_profiling/model/expectation_algorithms.py, src/pandas_profiling/model/handler.py, src/pandas_profiling/profile_report.py, tests/issues/test_issue664.py, tests/unit/test_ge_integration.py, tests/unit/test_ge_integration_expectations.py
Bootstrap the great-expectations setup for a dataset based on the semantic data types and metrics computed by pandas-profiling.
(includes minor bugfixes for json representation and slug)
=> integration with great expectations

README.md, docsrc/source/pages/resources.rst
Updates reference documentation and README documenting recent improvements to summary customization capabilities.
=> docs update

src/pandas_profiling/model/expectation_algorithms.py
=> fix: Add parse_strings_as_datetimes to datetime_expectations

src/pandas_profiling/report/formatters.py, tests/unit/test_formatters.py
=> Formatter exp

README.md, docsrc/source/pages/contribution_guidelines.rst, docsrc/source/pages/support.rst
=> Slack links

src/pandas_profiling/config_default.yaml, src/pandas_profiling/config_minimal.yaml, src/pandas_profiling/model/duplicates.py, tests/issues/test_issue725.py
=> feat(duplicates): make duplicates key configurable

docsrc/source/pages/changelog/v2_13_0.rst, src/pandas_profiling/model/correlations.py, src/pandas_profiling/model/describe.py, src/pandas_profiling/model/messages.py, src/pandas_profiling/model/sample.py, src/pandas_profiling/model/summary.py, src/pandas_profiling/model/summary_algorithms.py, src/pandas_profiling/report/presentation/flavours/html/templates/warnings/warning_duplicates.html, src/pandas_profiling/report/presentation/flavours/html/templates/warnings/warning_empty.html, src/pandas_profiling/report/presentation/flavours/widget/warnings.py, tests/unit/test_decorator.py, tests/unit/test_describe.py, tests/unit/test_example.py, tests/unit/test_summary.py, tests/unit/test_summary_algos.py
=> feat: Allow empty dataframe

.github/workflows/ci_test.yml, .github/workflows/release.yml, .github/workflows/tests.yml, Makefile
Coverage slows down the build matrix testing
=> Split tests and coverage in CI/CD

requirements.txt, src/pandas_profiling/model/summary_algorithms.py, src/pandas_profiling/model/typeset.py, src/pandas_profiling/model/typeset_relations.py, tests/unit/test_typeset_custom.py, tests/unit/test_typeset_default.py
=> build: Upgrade to Visions 0.7.1

docsrc/source/pages/resources.rst
Hello,
I created a detailed article for this project. It covers almost every element of the report generated and in the end, I have also described the way to deploy this report using streamlit.
=> Adding my blog link

examples/meteorites/meteorites.ipynb, examples/tutorials/modify_report_structure.ipynb, src/pandas_profiling/model/describe.py, src/pandas_profiling/model/spark/correlations_spark.py, src/pandas_profiling/model/spark/describe_counts_spark.py, src/pandas_profiling/model/spark/summary_spark.py, src/pandas_profiling/report/structure/overview.py, src/pandas_profiling/report/structure/variables/render_boolean.py, src/pandas_profiling/report/structure/variables/render_categorical.py, tests/backends/spark_backend/example.py
change cache to persist to use user-defined memory choice for persisting spark objects. .cache() is a wrapper for .persist(), but with a default option (which might not be what the user wants)
See https://stackoverflow.com/a/26882607
=> change cache to persist to use user-defined memory choice for persis

src/pandas_profiling/config.py
one proposed way to handle #373 and #538
as I don't have a better idea but I don't really like people proposing quick fixes without attempting them themselves, here it is
=> matplotlib Agg

src/pandas_profiling/model/pandas/correlations_pandas.py
This fixes #825 
Displaying order of columns on a Kendall Plot - 
Displaying order of columns on fixed Phi-K Plot -
=> Fixes Phi K correlation variable order

src/pandas_profiling/config.py, src/pandas_profiling/profile_report.py, tests/backends/spark_backend/test_descriptions_spark.py, tests/backends/spark_backend/test_report_spark.py
Create default settings for spark and
enable automatic switching in
ProfileReport based on input df type
=> feat(spark): enable default spark settings

.github/workflows/tests.yml, src/pandas_profiling/model/alerts.py, src/pandas_profiling/model/summary_algorithms.py, src/pandas_profiling/report/presentation/core/variable.py, src/pandas_profiling/visualisation/utils.py, tests/unit/test_example.py, tests/unit/test_modular.py, tests/unit/test_plot.py, tests/unit/test_serialize.py
https://devguide.python.org/devcycle/#end-of-life-branches
=> ci: end of life for python 3.6, include 3.9

src/pandas_profiling/model/spark/summary_spark.py
Fixes an error when using a data frame with IntegerType columns.
=> Adds a missing data type to the Spark series describe function

src/pandas_profiling/profile_report.py, src/pandas_profiling/visualisation/plot.py, tests/unit/test_plot.py, tests/unit/test_time_series.py
Auxiliar function that showcases the distribution of each entity's data across the time axis.
```python
from pandas_profiling.visualisation.plot import timeseries_heatmap
timeseries_heatmap(dataframe, "entity_column", "time_column")
```
=> feat: multi entity time series heatmap

src/pandas_profiling/config.py, src/pandas_profiling/profile_report.py
fix tsmode incorrectly setting samples configuration to None
=> fix: incorrect sample configuration

src/pandas_profiling/model/spark/correlations_spark.py, src/pandas_profiling/model/spark/missing_spark.py, tests/backends/spark_backend/test_correlations_spark.py, tests/backends/spark_backend/test_report_spark.py
Correlation test fixes, as well as one whitespace fix
=> feat: fix spark correlation tests

examples/usaairquality/usaairquality.ipynb, examples/usaairquality/usaairquality.py
This is an example notebook showcasing how to run the profiling with the time series metrics enabled
=> docs: time series feature example notebook

src/pandas_profiling/visualisation/plot.py
autocorrelation plot ignores the primary color definition
=> chore: adjust autocorrelation plot color

requirements.txt, src/pandas_profiling/profile_report.py, src/pandas_profiling/visualisation/plot.py
=> feat: add typechecking to profile report

.pre-commit-config.yaml, docsrc/source/conf.py, docsrc/source/pages/support_contrib/contribution_guidelines.rst, examples/features/correlation_auto_example.py, examples/usaairquality/usaairquality.ipynb, examples/usaairquality/usaairquality.py, setup.py
=> chore(actions): add local execution of pre-commit hook

src/pandas_profiling/compare_reports.py, src/pandas_profiling/visualisation/plot.py
- add report initialization validation
- ignore columns not present on the base report
- fix some pre-commit issues
=> feat: ignore columns not present on the base report

examples/report_comparison/comparison.ipynb, examples/report_comparison/comparison.py
Add a basic example of profile report comparison
=> feat: report comparison example

.github/semantic.yml, .github/workflows/merge-master.yml, .github/workflows/pull-request.yml
PR title and all Commit messages semantic validation:
- tool: https://github.com/Ezard/semantic-prs#configuration-options
- configuration:
```yaml
titleAndCommits: true
```
=> chore(actions): add changelog only on new releases and pr title validation

src/pandas_profiling/report/presentation/flavours/html/templates/sequence/grid.html, src/pandas_profiling/report/presentation/flavours/html/templates/variable_info.html, src/pandas_profiling/visualisation/plot.py
Updating the layout of variables information to give more space to the variable description
new:
old:
Also adjusted histogram layout:
new:
old:
=> feat: update variables layout

README.md
Reverts ydataai/pandas-profiling#1206
=> fix: revert"docs: change community links"

src/pandas_profiling/config.py, src/pandas_profiling/profile_report.py
small refactoring to move settings load to the settings class
=> chore: move config load

README.md
Changes slack links to discord.
=> docs: update community url

src/pandas_profiling/compare_reports.py
Fix the bug that caused the comparison report to ignore the comparison settings
=> fix: compare report ignoring config parameter

CONTRIBUTING.md, README.md, docsrc/source/_static/css/custom.css, docsrc/source/conf.py, docsrc/source/pages/getting_started/concepts.rst, docsrc/source/pages/getting_started/examples.rst, docsrc/source/pages/getting_started/overview.rst, docsrc/source/pages/support_contrib/contribution_guidelines.rst, docsrc/source/pages/tables/data_quality_alerts.csv, docsrc/source/pages/use_cases/time_series_datasets.rst
Update documentation and readme with datasets compare and time-series information
=> docs: update documents with compare and time-series reports

src/pandas_profiling/report/presentation/flavours/html/templates/frequency_table_small.html, src/pandas_profiling/report/presentation/flavours/html/templates/sequence/grid.html
adjust the layout of profile report for categorical variables
=> fix: adjust categorical variables layout 

docsrc/source/pages/use_cases/time_series_datasets.rst
=> docs: time-series doc example fix

src/ydata_profiling/report/structure/report.py
Lint is failing on develop and causing other PR's to fail the validation checks
=> fix: lint failing on develop

src/ydata_profiling/model/alerts.py
Unify the format of all alerts.
=> fix: Add punctuation marks in all alerts

requirements.txt
closes https://github.com/ydataai/ydata-profiling/issues/1284
=> chore: upgrade scipy version

README.md
=> chore: add contributors wall to README

src/ydata_profiling/report/presentation/flavours/html/templates/alerts.html
Fix incomplete sentence on alert comparison message
=> fix: incorrect alert comparison message

.github/workflows/tests.yml
Reason: https://github.com/actions/setup-python/issues/682
=> fix(actions): pin python 3.7 to 3.7.16

src/ydata_profiling/visualisation/plot.py
profiling comparison was failing when comparing the new Text type
=> fix: comparison report failing for text type

src/ydata_profiling/profile_report.py, src/ydata_profiling/report/structure/variables/render_timeseries.py, src/ydata_profiling/visualisation/plot.py
Added a section with the time-series plot to the details section, and improved the visibility of the plot comparison
=> feat: add ts plot to variables' section details

README.md, docsrc/source/pages/getting_started/overview.rst, setup.py
Add new references to the README
=> docs: update README

docsrc/source/pages/getting_started/examples.rst
=> fix: us air quality doc example link

README.md
=> docs: change from `zap` to `sparkles`

README.md
Update url of use cases, main integrations, and common issues.
=> docs: update README.html

src/ydata_profiling/model/typeset_relations.py
fixes https://github.com/ydataai/ydata-profiling/issues/1431
=> fix: to_category misshandling pd.NA

README.md
See also https://github.com/ydataai/ydata-profiling/issues/1445#issuecomment-1724792266
=> docs: add 📊 for 'Key features'

requirements.txt, src/ydata_profiling/__init__.py
pinned Numba version to avoid critical failure. The minimal version was based on the last version to support Python 3.7
closes https://github.com/ydataai/ydata-profiling/issues/1420
=> chore(deps): fix numba package version, and filter warns

src/ydata_profiling/report/presentation/flavours/html/templates/table.html
Fix mistyping on table template
=> fix: template syntax error

src/ydata_profiling/profile_report.py, src/ydata_profiling/report/formatters.py, tests/unit/test_comparison.py
Fix timespan missing listargs decoration and add unit test for comparison report of timeseries with pandas.Timedelta index.
=> fix: formatters for timedelta missing listargs decoration

src/ydata_profiling/model/spark/describe_supported_spark.py
Proposed fix for issue [#1350 ](https://github.com/ydataai/ydata-profiling/issues/1350)
=> fix: Update describe_supported_spark.py included fix for DivideByZero

.github/workflows/pull-request.yml
commitlint action is failing without running, downgrading the version to test
=> fix: downgrade commitlint action version

install.bat
Anyone can run this file to install all dependencies mentioned in the requirements.txt file.
=> chore: Create install.bat

setup.py
Update the setup.py file to enable 
`pip install -U ydata-profiling[notebook]`
=> fix: update setup file for notebook installation

src/ydata_profiling/model/pandas/correlations_pandas.py
Fixes issue #1527 while supporting different python versions: python 3.7 onwards.
=> fix: fix correlations issues whenever strings are present

docs/integrations/great_expectations.md
Commit f228b9595a4737d4249ea1da7f494bf77562ca30 moved the location of the Great Expectations example source. This PR adjusts sources to changes.
=> docs: update Great Expectations example reference
